on:
  workflow_call:
    inputs:
      java-version:
        type: string
      test:
        type: boolean
        default: true
      integration:
        type: boolean
        default: false

env:
  GH_PACKAGES_USR: ${{ secrets.GH_PACKAGES_USR }}
  GH_PACKAGES_PSW: ${{ secrets.GH_PACKAGES_PSW }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} # https://stackoverflow.com/a/71158878

jobs:
  test:
    if: ${{ inputs.test == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/clojure-setup
        with:
          java-version: ${{ inputs.java-version }}
      - run: clojure -M:test
  integration:
    if: ${{ inputs.integration == true }}
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
    steps:
      - run: if [ -z $SNOWFLAKE_PASSWORD ]; then echo "SNOWFLAKE_PASSWORD not set or empty"; exit 1; fi
      - uses: actions/checkout@v4
      - uses: ./.github/actions/clojure-setup
        with:
          java-version: ${{ inputs.java-version }}
      - run: clojure -M:integration
